project:
  type: website
  output-dir: docs
website:
  title: "m1keh0uk.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Viz
        menu:              
          - href: worldsfairs.qmd
            text: World's Fair
          - href: outerSpaceObjects.qmd
            text: Outer Space Objects
          - href: obamaTweets.qmd
            text: Obama's Tweets
          - href: planeSimulation.qmd
            text: Drunk Passenger Simualtion
          - href: WAI.qmd
            text: WAI measures
          - href: shinyWAI.qmd
            text: Interactive WAI
          - href: presentation.qmd
            text: End of Semester Presentaion

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

